# Generated by Django 4.1.4 on 2023-01-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Creator',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
