# Generated by Django 4.1.4 on 2023-01-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videodistribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='videos/thumbnails/'),
        ),
    ]
